/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2021-06-25 04:36:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.event;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.AtFileVO;
import vo.EventVO;
import java.util.List;
import vo.ConstVO;
import vo.MemVO;
import vo.CampHostVO;
import vo.AdminVO;

public final class select_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1624519418819L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	EventVO eventVO = (EventVO)request.getAttribute("eventVO");

	 List<AtFileVO> fileList = (List<AtFileVO>)request.getAttribute("fileList");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.3/css/all.css\" integrity=\"sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("</script>\r\n");
      out.write("<title>게시글 정보</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\ttable {\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\tborder-collapse: collapse;\r\n");
      out.write("\t\tline-height: 1.5;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable th,td{\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\tcolor: #369;\r\n");
      out.write("\t\tborder-bottom: 3px solid #036;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttable td {\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\tvertical-align: top;\r\n");
      out.write("\t\tborder-bottom: 1px solid #ccc;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttable td {\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\tborder-bottom: 1px solid #ccc;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\th1 {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.atag{\r\n");
      out.write("\t\ttext-align: center;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.bg-dark {\r\n");
      out.write("    background-color: #5a5c69 !important;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

HttpSession loginSession = request.getSession();
String loginType = (String) loginSession.getAttribute(ConstVO.LOGIN_TYPE);
MemVO memVO = (MemVO) loginSession.getAttribute("memVO");
CampHostVO hostVO = (CampHostVO) loginSession.getAttribute("hostVO");
AdminVO adminVO = (AdminVO) loginSession.getAttribute("adminVO");

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("\t<div class=\"container px-1\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"/\">\r\n");
      out.write("\t\t<img src=\"\thttp://localhost/images/logo.png\" alt=\"logo\" width=\"100px\"></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav> ");
      out.write("\r\n");
      out.write("\t<h2 align=\"center\"><i class=\"fas fa-book-open\">&nbsp;&nbsp;&nbsp;</i>이벤트</h2>\r\n");
      out.write("\t<br><br><br>\r\n");
      out.write("\t<table style=\"border: 1px solid white;\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th style=\"background-color: #669999; color: white;\">제&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 목</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(eventVO.getEvnTitle() );
      out.write("</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t");

							
						String date = eventVO.getEvnDate();
						date = date.substring(0, 10);
			
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"margin: auto;\" width=\"60%\"  height=\"100px; background-color: navy; color: white;\"><center>내&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 용</center></td>\r\n");
      out.write("\t\t\t<td>");
      out.print(eventVO.getEvnCon() );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"background-color: #669999; color: white;\">등록일</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(date );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"3\" height=\"300px;\"> \r\n");
      out.write("\t\t\t\t");
if(fileList != null){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
for(AtFileVO fileVO : fileList){ 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<img id=\"aaa\" src=\"");
      out.print(request.getContextPath() );
      out.write("/filedownload.do?fileId=");
      out.print(fileVO.getFileId());
      out.write("&fileNo=");
      out.print(fileVO.getFileNo());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t<p style=\"display: inline;\">첨부파일: </p>\r\n");
      out.write("\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath() );
      out.write("/filedownload.do?fileId=");
      out.print(fileVO.getFileId());
      out.write("&fileNo=");
      out.print(fileVO.getFileNo());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(fileVO.getFileOrigin() );
      out.write("\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t ");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t");

		// 관리자 이면
		if(ConstVO.LOGIN_TYPE_ADMIN.equals(loginType)){
		
	
      out.write("\r\n");
      out.write("\t<div class=\"atag\">\r\n");
      out.write("\t\t<a href=\"list.do\"><button class=\"btn btn-success\"><i class=\"far fa-edit\"></i>게시글 등록</button></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<a href=\"update.do?evnCode=");
      out.print(eventVO.getEvnCode() );
      out.write("\"><button class=\"btn btn-warning\"><i class=\"far fa-edit\"></i>게시글 수정</button></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<a href=\"delete.do?evnCode=");
      out.print(eventVO.getEvnCode() );
      out.write("\"><button class=\"btn btn-danger\"><i class=\"far fa-edit\"></i>게시글 삭제</button></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
