/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2021-06-25 04:37:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.crew;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class crewJoinThm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\timg{\r\n");
      out.write("\t\tborder-radius: 15px;\r\n");
      out.write("\t\twidth: 250px;\r\n");
      out.write("\t}\r\n");
      out.write("\timg:hover{\r\n");
      out.write("\t\tborder: 2px solid lightgray;\r\n");
      out.write("\t}\r\n");
      out.write("\th2{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t@import url(//fonts.googleapis.com/earlyaccess/nanummyeongjo.css);\r\n");
      out.write("\t\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tfont-family: 'Nanum Myeongjo', serif;\r\n");
      out.write("\t}\r\n");
      out.write("\t#logo{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");

String gen = request.getParameter("gen");
String act = request.getParameter("act");

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"logo\">\r\n");
      out.write("\t\t<img src=\"../images/crew.png\" alt=\"..?\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<h2>캠핑여행의 테마를 선택해주세요.</h2>\r\n");
      out.write("\t\t<br><br><br>\r\n");
      out.write("\t<div class=\"container\" style=\"width: 70%\">\r\n");
      out.write("\t<br><br><br>\r\n");
      out.write("\t\t<div style=\"text-align: center; width: calc(20%); float: left; overflow: hidden;\">\r\n");
      out.write("\t\t\t<h2>해안</h2>\r\n");
      out.write("\t\t\t<a href=\"crewJoin.do?key=thm&thm=해안&gen=");
      out.print(gen );
      out.write("&act=");
      out.print(act );
      out.write("\"><img alt=\"해안\" src=\"http://nstayidb.cafe24.com/arribada/tour/101.jpg\" height=\"300px\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"text-align: center; width: calc(20%); float: left; overflow: hidden;\">\r\n");
      out.write("\t\t\t<h2>자연</h2>\r\n");
      out.write("\t\t\t<a href=\"crewJoin.do?key=thm&thm=자연&gen=");
      out.print(gen );
      out.write("&act=");
      out.print(act );
      out.write("\"><img alt=\"자연\" src=\"https://papers.co/android/wp-content/uploads/papers.co-mi76-mountain-spring-view-sunrise-david-marcu-nature-6-wallpaper-1-250x400.jpg\" height=\"300px\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"text-align: center; width: calc(20%); float: left; overflow: hidden;\">\r\n");
      out.write("\t\t\t<h2>도시</h2>\r\n");
      out.write("\t\t\t<a href=\"crewJoin.do?key=thm&thm=도시&gen=");
      out.print(gen );
      out.write("&act=");
      out.print(act );
      out.write("\"><img alt=\"도시\" src=\"https://pds.joins.com/news/component/htmlphoto_mmdata/201505/07/htm_2015050723223750105011.jpg\" height=\"300px\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"text-align: center; width: calc(20%); float: left; overflow: hidden;\">\r\n");
      out.write("\t\t\t<h2>반려동물</h2>\r\n");
      out.write("\t\t\t<a href=\"crewJoin.do?key=thm&thm=반려동물&gen=");
      out.print(gen );
      out.write("&act=");
      out.print(act );
      out.write("\"><img alt=\"반려동물\" src=\"https://c.wallhere.com/photos/15/46/dog_bubbles_look-608053.jpg!d\" height=\"300px\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"text-align: center; width: calc(20%); float: left; overflow: hidden;\">\r\n");
      out.write("\t\t\t<h2>무관</h2>\r\n");
      out.write("\t\t\t<a href=\"crewJoin.do?key=thm&thm=무관&gen=");
      out.print(gen );
      out.write("&act=");
      out.print(act );
      out.write("\"><img alt=\"무관\" src=\"http://m.gagsital.com/web/product/medium/201707/2707_shop1_658932.jpg\" height=\"300px\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
