/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2021-06-25 05:45:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.crew;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.CrewreplyVO;
import java.util.List;
import vo.RecCrewVO2;
import vo.CrewThmVO;
import vo.CrewActVO;
import vo.RecCrewVO;
import vo.ConstVO;
import vo.MemVO;
import vo.CampHostVO;
import vo.AdminVO;

public final class crewView3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1624519418819L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	
	RecCrewVO2 rcv = (RecCrewVO2)request.getAttribute("rv");
List<CrewreplyVO> crv = (List<CrewreplyVO>)request.getAttribute("crv");

      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");

String startDate = rcv.getRecrStart();
	   startDate = startDate.substring(0,10);
String endDate = rcv.getRecrStart();
	   endDate = endDate.substring(0,10);
	   
String act = rcv.getActCode();
if("a001".equals(act)) {
	act= "등산";
}else if("a002".equals(act)){
	act = "낚시";
}else if("a003".equals(act)){
	act = "오락";
}else if("a004".equals(act)){
	act = "힐링";
}else if("a005".equals(act)){
	act = "무관";
}
String thm = rcv.getTmCode();
if("t001".equals(thm)) {
	thm = "해안";
}else if("t002".equals(thm)){
	thm = "자연";
}else if("t003".equals(thm)){
	thm = "도시";
}else if("t004".equals(thm)){
	thm = "반려동물";
}else if("t005".equals(thm)){
	thm = "무관";
}

      out.write("\r\n");
      out.write("<head>\r\n");

int curr = rcv.getRecrCurrnum();
int need = rcv.getRecrNeednum();
int add = need - curr;

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>게시글</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function proc() {\r\n");
      out.write("\tif(");
      out.print(add );
      out.write(" <= 0){\r\n");
      out.write("\t\talert(\"인원을 체크해주세요\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"가입 성공하였습니다!\")\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

HttpSession loginSession = request.getSession();
String loginType = (String) loginSession.getAttribute(ConstVO.LOGIN_TYPE);
MemVO memVO = (MemVO) loginSession.getAttribute("memVO");
CampHostVO hostVO = (CampHostVO) loginSession.getAttribute("hostVO");
AdminVO adminVO = (AdminVO) loginSession.getAttribute("adminVO");

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("\t<div class=\"container px-1\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"/\">\r\n");
      out.write("\t\t<img src=\"\thttp://localhost/images/logo.png\" alt=\"logo\" width=\"100px\"></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav> ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"width: 50%; border: 1px solid black;\">\r\n");
      out.write("\t\t<p>제목 : ");
      out.print(rcv.getRecrTitle() );
      out.write("</p>\r\n");
      out.write("\t\t<p>날짜 : ");
      out.print(startDate );
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print(endDate );
      out.write("</p>\r\n");
      out.write("\t\t<p>인원 : ");
      out.print(rcv.getRecrCurrnum() );
      out.write('/');
      out.print(rcv.getRecrNeednum() );
      out.write("</p>\r\n");
      out.write("\t\t<p>테마 : ");
      out.print(thm );
      out.write(" / 활동 : ");
      out.print(act );
      out.write("</p>\r\n");
      out.write("\t\t<p>내용 : ");
      out.print(rcv.getRecrContent() );
      out.write(" </p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<form method=\"post\" action=\"");
      out.print(request.getContextPath() );
      out.write("/crew/crewRply.do\">\r\n");
      out.write("\t\t\t<textarea rows=\"3\" cols=\"30\" name=\"replyCon\"></textarea>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"crewCode\" value=\"");
      out.print(rcv.getCrewCode());
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"memId\" value=\"");
      out.print(memVO.getMemId() );
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"memCode\" value=\"");
      out.print(memVO.getMemCode() );
      out.write("\">\r\n");
      out.write("\t\t\t<button type=\"submit\">등록</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");
	
		if(crv!=null){
			int rplySize = crv.size();
			
			if(rplySize > 0)
			for(int i=0; i < rplySize; i++){
				
      out.write("\r\n");
      out.write("\t\t\t\t<p>");
      out.print(crv.get(i).getMemId() );
      out.write(" >> ");
      out.print(crv.get(i).getReplyCon() );
      out.write(" </p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
	
			}
			
		}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
