/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2021-07-21 10:19:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.AdminVO;
import vo.ConstVO;
import vo.MemVO;
import vo.CampHostVO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>이짝워뗘</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap icons-->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template-->\r\n");
      out.write("<link href=\"css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Custom fonts for this template-->\r\n");
      out.write("<link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#headerImg {\r\n");
      out.write("\tbackground-size: 100% 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tem1, #tem2, #tem3, #tem4 {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tem1:hover, #tem2:hover, #tem3:hover, #tem4:hover {\r\n");
      out.write("\tbackground-color: #EAEAEA;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction fnMove(seq) {\r\n");
      out.write("\t\tvar location = document.querySelector(\"#tema\" + seq).offsetTop;\r\n");
      out.write("\t\twindow.scrollTo({\r\n");
      out.write("\t\t\ttop : location,\r\n");
      out.write("\t\t\tbehavior : 'smooth'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");

HttpSession loginSession = request.getSession();
String loginType = (String) loginSession.getAttribute(ConstVO.LOGIN_TYPE);
MemVO memVO = (MemVO) loginSession.getAttribute("memVO");
CampHostVO hostVO = (CampHostVO) loginSession.getAttribute("hostVO");
AdminVO adminVO = (AdminVO) loginSession.getAttribute("adminVO");

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"d-flex flex-column h-100\">\r\n");
      out.write("\t<main class=\"flex-shrink-0\"> \r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Navigation--> \r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("\t<div class=\"container px-1\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("\t\t<img src=\"images/logo.png\" alt=\"logo\" width=\"100px\"></a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t");

			// 사용자 로그인시 항목
			if(ConstVO.LOGIN_TYPE_USER.equals(loginType) ) {
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/event/list.do\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/host/hostNotice.do\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" id=\"navbarDropdownBlog\" href=\"#\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">문의사항</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"navbarDropdownBlog\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/qna/list.do\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/faq.do\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" id=\"navbarDropdownPortfolio\"\r\n");
      out.write("\t\t\t\t\thref=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"><i class=\"fas fa-user-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"navbarDropdownPortfolio\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");

						if(memVO == null) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"login.do\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/clientjoin.do\">일반회원 회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/hostjoin.do\">호스트 회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"logout.do\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"memMyPage.jsp\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
	
			// 업체 로그인시 항목
			}else if(ConstVO.LOGIN_TYPE_HOST.equals(loginType)){
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/event/list.do\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/host/hostNotice.do\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" id=\"navbarDropdownBlog\" href=\"#\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">문의사항</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"navbarDropdownBlog\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/qna/list.do\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/faq.do\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" id=\"navbarDropdownPortfolio\"\r\n");
      out.write("\t\t\t\t\thref=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"><i class=\"fas fa-user-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"navbarDropdownPortfolio\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");

						if(hostVO == null) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"login.do\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/clientjoin.do\">일반회원 회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/hostjoin.do\">호스트 회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"logout.do\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"hostMyPage.jsp\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");

			// 관리자 로그인시 항목	
			}else if(ConstVO.LOGIN_TYPE_ADMIN.equals(loginType)){
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/event/list.do\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/host/hostNotice.do\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" id=\"navbarDropdownBlog\" href=\"#\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">문의사항</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"navbarDropdownBlog\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/qna/list.do\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/faq.do\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" id=\"navbarDropdownPortfolio\"\r\n");
      out.write("\t\t\t\t\thref=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"><i class=\"fas fa-user-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"navbarDropdownPortfolio\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");

						if(adminVO == null) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"login.do\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/clientjoin.do\">일반회원 회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/hostjoin.do\">호스트 회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"logout.do\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"portfolio-item.html\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
	
			// 로그인 정보가 없을 때 항목		
			}else {
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/event/list.do\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/host/hostNotice.do\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" id=\"navbarDropdownBlog\" href=\"#\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">문의사항</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"navbarDropdownBlog\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/qna/list.do\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/faq.do\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" id=\"navbarDropdownPortfolio\"\r\n");
      out.write("\t\t\t\t\thref=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"><i class=\"fas fa-user-circle\"></i></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"navbarDropdownPortfolio\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");

						if(memVO == null || hostVO == null) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"login.do\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/clientjoin.do\">일반회원 회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"/hostjoin.do\">호스트 회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"logout.do\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"portfolio-item.html\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\t\r\n");
      out.write("\t\t\t");

			}
			
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav> \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Header--> \r\n");
      out.write("\t<header id=\"headerImg\" class=\"bg-dark py-5\"\r\n");
      out.write("\t\tstyle=\"width:100%; background-image: url('images/tree.jpg');\">\r\n");
      out.write("\t<div class=\"container px-5\">\r\n");
      out.write("\t\t<div class=\"row gx-5 align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-8 col-xl-7 col-xxl-6\">\r\n");
      out.write("\t\t\t\t<div class=\"my-5 text-center text-xl-start\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"display-5 fw-bolder text-white mb-2\">같이 캠핑 가볼텨?</h1>\r\n");
      out.write("\t\t\t\t\t<p class=\"lead fw-bold text-white mb-4\" style=\"color: red;\">캠핑족들\r\n");
      out.write("\t\t\t\t\t\t모여라! 같이 캠핑가자</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn-primary btn-lg px-4 me-sm-3\" href=\"/crew/crewMake.do\">크루\r\n");
      out.write("\t\t\t\t\t\t\t모집하기</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn  btn-primary1 btn-lg px-4\" href=\"/crew/crewJoin.do\"\r\n");
      out.write("\t\t\t\t\t\t\t\">크루 신청하기</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xl-5 col-xxl-6 d-none d-xl-block text-center\">\r\n");
      out.write("\t\t\t\t<a href=\"http://localhost/event/view.do?evnCode=12\"><img class=\"img-fluid rounded-3 my-5\"\r\n");
      out.write("\t\t\t\t\tsrc=\"images/market.jpg\" alt=\"...\" / width=\"600px\" height=\"400px\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</header> \r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Features section--> \r\n");
      out.write("\t<section class=\"py-5\" id=\"tema1\">\r\n");
      out.write("\t<div class=\"container px-5 my-5\">\r\n");
      out.write("\t\t<div class=\"row gx-5 justify-content-center\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-8 col-xl-6\">\r\n");
      out.write("\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"fw-bolder\">어떤 곳을 갈까?</h2>\r\n");
      out.write("\t\t\t\t\t<p class=\"lead fw-normal text-muted mb-5\">다양한 캠핑장 카테고리를 통해<br>자신의 취향에 맞는 캠핑장을 선택해보자!</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row gx-5\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 mb-5\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100 shadow border-0\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a class=\"text-decoration-none\" href=\"IcampNature.jsp\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\" src=\"images/camping2.jpg\" alt=\"...\" />\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t\t\t<a class=\"text-decoration-none  link-dark \" href=\"lcampNature.jsp\"> \r\n");
      out.write("\t\t\t\t\t<div class=\"card-body p-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"badge bg-primary bg-gradient rounded-pill mb-2\">Nature</div> \r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title mb-3\">맑은 공기를 가진 자연</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-0\">A place where you can heal with friends and family in a nature full of fresh air.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 mb-5\">\r\n");
      out.write("\t\t\t<a class=\"text-decoration-none link-dark stretched-link\" href=\"campSea.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100 shadow border-0\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/camping1.jpg\"  alt=\"....\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body p-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"badge bg-primary bg-gradient rounded-pill mb-2\">Sea</div>\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title mb-3\">뷰가 멋진 해안가</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-0\">A place where you can spend quality time with your lovers and family on the beach with stunning views.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 mb-5\">\r\n");
      out.write("\t\t\t<a class=\"text-decoration-none link-dark stretched-link\" href=\"campCity.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100 shadow border-0\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/camping3.jpg\"  alt=\".....\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body p-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"badge bg-primary bg-gradient rounded-pill mb-2\">City</div>\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title mb-3\">야경이 빛나는 도시</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-0\">A place where you can heal with the beautiful night view shining even in the dark.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 mb-5\">\r\n");
      out.write("\t\t\t<a class=\"text-decoration-none link-dark stretched-link\" href=\"campPartner.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100 shadow border-0\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/camping4.jpg\"  alt=\".......\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body p-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"badge bg-primary bg-gradient rounded-pill mb-2\">Partner</div>\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title mb-3\">반려동물 동반</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-0\">A place where you can enjoy camping with your beloved pet.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section> <!-- Blog preview section--> <section class=\"py-5\" id=\"tema2\">\r\n");
      out.write("\t<div class=\"container px-5 my-5\">\r\n");
      out.write("\t\t<div class=\"row gx-5 justify-content-center\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-8 col-xl-6\">\r\n");
      out.write("\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"fw-bolder\">스트레스 뿌시러 가자!</h2>\r\n");
      out.write("\t\t\t\t\t<p class=\"lead fw-normal text-muted mb-5\">스트레스 푸는 방법도 다양하게!<br>스트레스 풀 수 있는 캠핑장을 선택해보자!</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row gx-5\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 mb-5\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100 shadow border-0\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/climbing.jpg\" alt=\"...\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body p-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"badge bg-primary bg-gradient rounded-pill mb-2\">Climbing</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"text-decoration-none link-dark stretched-link\" href=\"campClimb.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title mb-3\">산책, 등산</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-0\">There's a trail to take a walk, a mountain to climb.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 mb-5\">\r\n");
      out.write("\t\t\t<a class=\"text-decoration-none link-dark stretched-link\" href=\"campFish.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100 shadow border-0\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/water.jpg\" alt=\"...\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body p-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"badge bg-primary bg-gradient rounded-pill mb-2\">Fishing</div>\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title mb-3\">낚시, 수상레저</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-0\">You can fish, water leisure, water play.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 mb-5\">\r\n");
      out.write("\t\t\t<a class=\"text-decoration-none link-dark stretched-link\" href=\"campEnter.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100 shadow border-0\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/jumping.jpg\" alt=\"...\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body p-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"badge bg-primary bg-gradient rounded-pill mb-2\">Entertainment</div>\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title mb-3\">놀이, 오락</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-0\">It's full of fun and active activities.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 mb-5\">\r\n");
      out.write("\t\t\t<a class=\"text-decoration-none link-dark stretched-link\" href=\"campHeal.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"card h-100 shadow border-0\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/healing.jpg\" alt=\"...\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body p-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"badge bg-primary bg-gradient rounded-pill mb-2\">Healing</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-title mb-3\">힐링 그 자체</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text mb-0\">Quiet, relaxed, healing with a cup of coffee.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section> \r\n");
      out.write("\t</main>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer-->\r\n");
      out.write("\t<footer class=\"bg-dark py-4 mt-auto\">\r\n");
      out.write("\t<div class=\"container px-5\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"row align-items-center justify-content-between flex-column flex-sm-row\">\r\n");
      out.write("\t\t\t<div class=\"col-auto\">\r\n");
      out.write("\t\t\t\t<div class=\"small m-0 text-white\">Middle Project 2021.06.25</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-auto\">\r\n");
      out.write("\t\t\t\t<a class=\"link-light small\" href=\"#!\">Privacy</a> <span\r\n");
      out.write("\t\t\t\t\tclass=\"text-white mx-1\">&middot;</span> <a class=\"link-light small\"\r\n");
      out.write("\t\t\t\t\thref=\"#!\">Terms</a> <span class=\"text-white mx-1\">&middot;</span> <a\r\n");
      out.write("\t\t\t\t\tclass=\"link-light small\" href=\"#!\">Contact</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap core JavaScript-->\r\n");
      out.write("\t<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Core plugin JavaScript-->\r\n");
      out.write("\t<script src=\"vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for all pages-->\r\n");
      out.write("\t<script src=\"js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap core JS-->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<!-- Core theme JS-->\r\n");
      out.write("\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
